### PR TITLE
Add limit switches to the arm and intake systems

### LINKED ISSUE #56: Limit Switches
We will have 3 limit switches. One will be in the path of the bottom piece of the arm and the two others will be for the sides of the intake. When the one for the arm is activated, the bottom of the arm should not move any further toward the robot and when either of the two for the intake are activated, the intake should not move toward the robot until that limit switch is no longer pressed.

### PR DESCRIPTION
**Pull request by jwong101**
Two limit switches were added to the intake system for the intake arms and one limit switch was added to the arm system for the bottom arm. These limit switches stop the respective motors in each system from moving forward if a limit switch is pressed. Testing for the limit switches were added in the unit test for each system. This closes #56.

### CODE REVIEW

**Comment by LoadingPleaseWait** [comment]
The logic for the intake is backwards. It should be prevented from moving further toward the robot to prevent damage to the robot.

**Comment by LoadingPleaseWait** [comment]
The logic is still backwards. The intake needs to be prevented from moving further toward the robot when the limit switches are closed.

**Comment by jwong101** [comment]
-Speed is towards and +Speed is away from the robot now.

**Comment by LoadingPleaseWait** [comment]
I didn't see that at first. You're correct.

**Pull request merged**
